apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prompt2ai-db.fullname" . }}
  labels:
    {{- include "prompt2ai-db.labels" . | nindent 4 }}
spec:
  {{- with .Values.storage }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .requestedSize }}
  {{- end }}  
