{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "prompt2ai.fullname" . }}-app-pv
  labels:
    app.kubernetes.io/name: prompt2ai
    app.kubernetes.io/instance: prompt2ai
    app: prompt2ai
spec:
  storageClassName: {{ include "prompt2ai.fullname" . }}-app-pv
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.localPath }}
{{- end }}